name: Java Maven and Trivy Scan

on:
  workflow_dispatch:

jobs:

  build:
    name: Java Maven Build
    runs-on: [label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Compile Maven project
        run: mvn compile


  trivy-fs-scan:
    name: Trivy FS Scan
    runs-on: [label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check Trivy version
        run: trivy --version

      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .
