name: Java Maven and Trivy Scan

on:
  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

jobs:

  build:
    name: Java Maven Build
    runs-on: [label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Check generated JAR
        run: |
          echo "JAR files:"
          find target -name "*.jar" -type f


  trivy-fs-scan:
    name: Trivy FS Scan
    runs-on: [label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check Trivy version
        run: trivy --version

      - name: Trivy Filesystem Scan
        run: trivy fs --format table -o fs-report.json .


  docker-build:
    name: Build Docker Image
    runs-on: [label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Check generated JAR
        run: |
          echo "JAR files:"
          find target -name "*.jar" -type f

      - name: Check Docker version
        run: docker --version

      - name: Build Docker image
        run: docker build -t my-java-app:latest .

      - name: List Docker images
        run: docker images
     
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Tag Docker image
        run: |
          docker tag my-java-app:latest ghcr.io/${{ github.repository_owner }}/my-java-app:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-java-app:latest
